<?php
/**
 * Created by PhpStorm.
 * Date: 19-4-19
 * Time: 下午1:16
 */

namespace App\Constants;

/**
 * Interface AdminPermissions
 * @package App\Constants
 */
interface AdminPermissions
{
    const SUPER = "ADMIN_PERM_SUPER";

    // 证书增删改查
    const R_CERTIFICATE = "AMIDN_PERM_R_CERTIFICATE";
    const CU_CERTIFICATE = "AMIDN_PERM_CU_CERTIFICATE";
    const D_CERTIFICATE = "AMIDN_PERM_D_CERTIFICATE";

    // 地域增删改查
    const R_REGION = "ADMIN_PERM_R_REGION";
    const CU_REGION = "ADMIN_PERM_CU_REGION";
    const D_REGION = "ADMIN_PERM_D_REGION";

    // 流量共享组增删改查
    const R_TRAFFIC_SHARE_GROUP = "ADMIN_PERM_R_TRAFFIC_SHARE_GROUP";
    const CU_TRAFFIC_SHARE_GROUP = "ADMIN_PERM_CU_TRAFFIC_SHARE_GROUP";
    const D_TRAFFIC_SHARE_GROUP = "ADMIN_PERM_D_TRAFFIC_SHARE_GROUP";

    // 可用区增删改查
    const R_ZONE = "ADMIN_PERM_R_ZONE";
    const CU_ZONE = "ADMIN_PERM_CU_ZONE";
    const D_ZONE = "ADMIN_PERM_D_ZONE";

    // 计算节点增删改查
    const R_COMPUTE_NODE = "ADMIN_PERM_R_COMPUTE_NODE";
    const CU_COMPUTE_NODE = "ADMIN_PERM_CU_COMPUTE_NODE";
    const D_COMPUTE_NODE = "ADMIN_PERM_D_COMPUTE_NODE";

    // 公共镜像增删改查
    const R_PUBLIC_IMAGE = "ADMIN_PERM_R_PUBLIC_IMAGE";
    const CU_PUBLIC_IMAGE = "ADMIN_PERM_CU_PUBLIC_IMAGE";
    const D_PUBLIC_IMAGE = "ADMIN_PERM_D_PUBLIC_IMAGE";

    // 公共ISO增删改
    // const R_PUBLIC_ISO = "ADMIN_PERM_R_PUBLIC_ISO";
    const CU_PUBLIC_ISO = "ADMIN_PERM_CU_PUBLIC_ISO";
    const D_PUBLIC_ISO = "ADMIN_PERM_D_PUBLIC_ISO";

    // 公共Floppy增删改
    // const R_PUBLIC_FLOPPY = "ADMIN_PERM_R_PUBLIC_FLOPPY";
    const CU_PUBLIC_FLOPPY = "ADMIN_PERM_CU_PUBLIC_FLOPPY";
    const D_PUBLIC_FLOPPY = "ADMIN_PERM_D_PUBLIC_FLOPPY";

    // 计算实例规格增删改查
    const R_COMPUTE_INSTANCE_PACKAGE = "ADMIN_PERM_R_COMPUTE_INSTANCE_PACKAGE";
    const CU_COMPUTE_INSTANCE_PACKAGE = "ADMIN_PERM_CU_COMPUTE_INSTANCE_PACKAGE";
    const D_COMPUTE_INSTANCE_PACKAGE = "ADMIN_PERM_D_COMPUTE_INSTANCE_PACKAGE";

    // IP地址池增删改查
    const R_IP_POOL = "ADMIN_PERM_R_IP_POOL";
    const CU_IP_POOL = "ADMIN_PERM_CU_IP_POOL";
    const D_IP_POOL = "ADMIN_PERM_D_IP_POOL";

    const R_IP_ASSIGNMENT = "ADMIN_PERM_R_IP_ASSIGNMENT"; // 浏览IP分配
    const CONVERT_IP_ASSIGNMENT = "ADMIN_PERM_CONVERT_IP_ASSIGNMENT"; // 转换IP类型
    const BIND_IP_ASSIGNMENT = "ADMIN_PERM_BIND_IP_ASSIGNMENT"; // 绑定IP
    const UNBIND_IP_ASSIGNMENT = "ADMIN_PERM_UNBIND_IP_ASSIGNMENT"; // 解绑IP
    const ALLOCATE_IP_ASSIGNMENT = "ADMIN_PERM_ASSIGN_IP_ASSIGNMENT"; // 分配IP
    const RELEASE_IP_ASSIGNMENT = "ADMIN_PERM_RELEASE_IP_ASSIGNMENT"; // 释放IP
    const UPDATE_IP_ASSIGNMENT = "ADMIN_PERM_UPDATE_IP_ASSIGNMENT"; // 更新IP属性

    const R_USER_QUOTA = "ADMIN_R_USER_QUOTA"; // 浏览用户配额
    const CU_USER_QUOTA = "ADMIN_CU_USER_QUOTA"; // 创建&编辑用户配额
    const D_USER_QUOTA = "ADMIN_D_USER_QUOTA"; // 删除用户配额

    const R_USER = "ADMIN_R_USER_QUOTA"; // 浏览用户
    const ADD_CREDIT_TO_USER = "ADMIN_PERM_ADD_CREDIT_TO_USER"; // 添加用户余额
    const REMOVE_CREDIT_FROM_USER = "ADMIN_PERM_REMOVE_CREDIT_FROM_USER"; // 扣除用户余额
    const LOGIN_AS_USER = "ADMIN_PERM_LOGIN_AS_USER"; // 以用户身份登录
    const SUSPEND_USER = "ADMIN_PERM_SUSPEND_USER"; // 锁定用户
    const UNSUSPEND_USER = "ADMIN_PERM_UNSUSPEND_USER"; // 解锁用户
    const CU_USER = "ADMIN_PERM_CU_USER"; // 创建/修改用户
    const D_USER = "ADMIN_PERM_D_USER"; // 删除用户

    const R_COMPUTE_INSTANCE = "ADMIN_PERM_R_COMPUTE_INSTANCE"; // 浏览计算实例
    const OPERATE_COMPUTE_INSTANCE = "ADMIN_PERM_OPERATE_COMPUTE_INSTANCE"; // 操作计算实例
    const SUSPEND_COMPUTE_INSTANCE = "ADMIN_PERM_SUSPEND_COMPUTE_INSTANCE"; // 锁定计算实例
    const UNSUSPEND_COMPUTE_INSTANCE = "ADMIN_PERM_UNSUSPEND_COMPUTE_INSTANCE"; // 解锁计算实例
    const U_COMPUTE_INSTANCE = "ADMIN_PERM_U_COMPUTE_INSTANCE"; // 更新计算实例属性
    const D_COMPUTE_INSTANCE = "ADMIN_PERM_D_COMPUTE_INSTANCE"; // 删除计算实例

    const R_LOCAL_VOLUME = "ADMIN_PERM_R_LOCAL_VOLUME"; // 浏览本地卷
    const ATTACH_LOCAL_VOLUME = "ADMIN_PERM_ATTACH_LOCAL_VOLUME"; // 连接本地卷
    const DETACH_LOCAL_VOLUME = "ADMIN_PERM_DETACH_LOCAL_VOLUME"; // 分离本地卷
    const RELEASE_LOCAL_VOLUME = "ADMIN_PERM_RELEASE_LOCAL_VOLUME"; // 释放本地卷
    const TOGGLE_PROTECT_MODE_LOCAL_VOLUME = "ADMIN_PERM_TOGGLE_PROTECT_MODE_LOCAL_VOLUME"; // 开关保护模式
    const TOGGLE_PRIMARY_BOOTABLE_DISK_LOCAL_VOLUME = "ADMIN_PERM_TOGGLE_PRIMARY_BOOTABLE_DISK_LOCAL_VOLUME"; // 设定默认引导盘
    const CHANGE_BUS_LOCAL_VOLUME = "ADMIN_PERM_CHANGE_BUS_LOCAL_VOLUME";
    const RESIZE_LOCAL_VOLUME = "ADMIN_PERM_RESIZE_LOCAL_VOLUME";

    const R_CURRENCY = "ADMIN_PERM_R_CURRENCY"; // 浏览货币
    const CU_CURRENCY = "ADMIN_PERM_CU_CURRENCY"; // 创建/编辑货币
    const D_CURRENCY = "ADMIN_PERM_D_CURRENCY"; // 删除货币

    const CRUD_PAYMENT_MODULE_CONFIGURATION = "ADMIN_PERM_CRUD_PAYMENT_MODULE_CONFIGURATION"; // 管理付款模块配置

    const CUD_TICKET_DEPARTMENT = "ADMIN_PERM_CUD_TICKET_DEPARTMENT"; // 创建/编辑/删除工单部门

    const R_TICKET = "ADMIN_PERM_R_TICKET"; // 浏览工单
    const MAKE_REPLY_TO_TICKET = "ADMIN_PERM_MAKE_REPLY_TO_TICKET"; // 回复工单
    const U_TICKET = "ADMIN_PERM_U_TICKET"; // 修改工单
    const D_TICKET = "ADMIN_PERM_D_TICKET"; // 删除工单

    const R_PAYMENT_TRADE = "ADMIN_PERM_R_PAYMENT_TRADE"; // 浏览充值订单
    const MARK_SUCCESS_PAYMENT_TRADE = "ADMIN_PERM_MARK_SUCCESS_PAYMENT_TRADE"; // 标记充值订单为已完成
    const MARK_CANCELLED_PAYMENT_TRADE = "ADMIN_PERM_MARK_CANCELLED_PAYMENT_TRADE"; // 标记充值订单为已取消
    const REFUND_PAYMENT_TRADE = "ADMIN_PERM_REFUND_PAYMENT_TRADE"; // 退款
    const U_PAYMENT_TRADE = "ADMIN_PERM_U_PAYMENT_TRADE"; // 编辑充值订单

    const CANCEL_PAYMENT_TRADE_REFUND = "ADMIN_PERM_CANCEL_PAYMENT_TRADE_REFUND"; // 取消退款
    const COMMIT_PAYMENT_TRADE_REFUND = "ADMIN_PERM_COMMIT_PAYMENT_TRADE_REFUND"; // 完成退款
    const U_STATUS_PAYMENT_TRADE_REFUND = "ADMIN_PERM_U_STATUS_PAYMENT_TRADE_REFUND"; // 更改退款订单状态

    const U_SELF_ADMIN = "ADMIN_PERM_U_SELF_ADMIN"; // 管理员更新自己帐号信息

    const R_BILLING_STATISTICS = "ADMIN_PERM_R_BULLING_STATISTICS"; // 浏览财务统计
}